(function(){var getElementsByClassName=function(e,t,n){if(document.getElementsByClassName){getElementsByClassName=function(e,t,n){n=n||document;var r=n.getElementsByClassName(e),i=t?new RegExp("\\b"+t+"\\b","i"):null,s=[],o;for(var u=0,a=r.length;u<a;u+=1){o=r[u];if(!i||i.test(o.nodeName)){s.push(o)}}return s}}else if(document.evaluate){getElementsByClassName=function(e,t,n){t=t||"*";n=n||document;var r=e.split(" "),i="",s="http://www.w3.org/1999/xhtml",o=document.documentElement.namespaceURI===s?s:null,u=[],a,f;for(var l=0,c=r.length;l<c;l+=1){i+="[contains(concat(' ', @class, ' '), ' "+r[l]+" ')]"}try{a=document.evaluate(".//"+t+i,n,o,0,null)}catch(h){a=document.evaluate(".//"+t+i,n,null,0,null)}while(f=a.iterateNext()){u.push(f)}return u}}else{getElementsByClassName=function(e,t,n){t=t||"*";n=n||document;var r=e.split(" "),i=[],s=t==="*"&&n.all?n.all:n.getElementsByTagName(t),o,u=[],a;for(var f=0,l=r.length;f<l;f+=1){i.push(new RegExp("(^|\\s)"+r[f]+"(\\s|$)"))}for(var c=0,h=s.length;c<h;c+=1){o=s[c];a=false;for(var p=0,d=i.length;p<d;p+=1){a=i[p].test(o.className);if(!a){break}}if(a){u.push(o)}}return u}}return getElementsByClassName(e,t,n)}
!function(e,t){typeof module!="undefined"?module.exports=t():typeof define=="function"&&typeof define.amd=="object"?define(t):this[e]=t()}("domready",function(e){function p(e){h=1;while(e=t.shift())e()}var t=[],n,r=!1,i=document,s=i.documentElement,o=s.doScroll,u="DOMContentLoaded",a="addEventListener",f="onreadystatechange",l="readyState",c=o?/^loaded|^c/:/^loaded|c/,h=c.test(i[l]);return i[a]&&i[a](u,n=function(){i.removeEventListener(u,n,r),p()},r),o&&i.attachEvent(f,n=function(){/^c/.test(i[l])&&(i.detachEvent(f,n),p())}),e=o?function(n){self!=top?h?n():t.push(n):function(){try{s.doScroll("left")}catch(t){return setTimeout(function(){e(n)},50)}n()}()}:function(e){h?e():t.push(e)}})
var widgets=function(){var timelines;timelines=getElementsByClassName('wordpress-timeline');for(var i=0;i<timelines.length;i++){var timeline=timelines[i];var width=((null==timeline.getAttribute('width'))?300:timeline.getAttribute('width'));var height=((null==timeline.getAttribute('height'))?500:timeline.getAttribute('height'));var href=timeline.getAttribute('href');if(href.indexOf('https://')==0)
href=href.substring(8);if(href.indexOf('http://')==0)
href=href.substring(7);if(href.substr(-1)=='/')
href=href.substr(0,href.length-1);var iframe=document.createElement('iframe');var iframe_url='//widgets.wp.com/timeline/index.html';iframe_url+='#blog='+href;iframe_url+=((null==timeline.getAttribute('lang'))?'':'&lang='+timeline.getAttribute('lang'));iframe_url+=((null==timeline.getAttribute('data-theme'))?'&theme=light':'&theme='+timeline.getAttribute('data-theme'));iframe_url+=((null==timeline.getAttribute('data-link-color'))?'':'&link_color='+timeline.getAttribute('data-link-color'));iframe_url+=((null==timeline.getAttribute('data-show-gravatars'))?'':'&show_gravatars='+timeline.getAttribute('data-show-gravatars'));iframe_url+='&width='+width;iframe_url+='&height='+height;iframe.setAttribute('src',iframe_url);iframe.setAttribute('width',width);iframe.setAttribute('height',height);iframe.setAttribute('frameborder','0');iframe.setAttribute('scrolling','no');timeline.parentNode.replaceChild(iframe,timeline);}
var follow_buttons;follow_buttons=getElementsByClassName('wordpress-follow-button');for(var i=0;i<follow_buttons.length;i++){var button=follow_buttons[i];var width='100%';var height=20;var href=button.getAttribute('href');if(href.indexOf('https://')==0)
href=href.substring(8);if(href.indexOf('http://')==0)
href=href.substring(7);if(href.substr(-1)=='/')
href=href.substr(0,href.length-1);var iframe=document.createElement('iframe');var iframe_url='//widgets.wp.com/follow/index.html';iframe_url+='#href='+href;iframe_url+=((null==button.getAttribute('data-lang'))?'':'&lang='+button.getAttribute('data-lang'));iframe_url+=((null==button.getAttribute('data-blog'))?'':'&blog='+encodeURIComponent(button.getAttribute('data-blog')));iframe_url+=((null==button.getAttribute('data-show-follower-count'))?'':'&show_follower_count='+encodeURIComponent(button.getAttribute('data-show-follower-count')));iframe_url+=((null==button.getAttribute('data-show-blog-name'))?'':'&show_blog_name='+encodeURIComponent(button.getAttribute('data-show-blog-name')));iframe.setAttribute('src',iframe_url);iframe.setAttribute('width',width);iframe.setAttribute('height',height);iframe.setAttribute('frameborder','0');iframe.setAttribute('scrolling','no');button.parentNode.replaceChild(iframe,button);}
var arg,embedArgs,iframe,iframeURL,s,uniqueID,wpEmbed,wpembeds=getElementsByClassName('wordpress-wpembed'),wpembedsCounter=0;for(i=0;i<wpembeds.length;i++){embedArgs={};iframe=document.createElement('iframe');iframeURL='https://widgets.wp.com/wpembed/index.html?';uniqueID=0;wpembed=wpembeds[i];embedArgs.gravatars=(wpembed.getAttribute('data-show-gravatars')==='false')?false:true;embedArgs.language=wpembed.getAttribute('data-lang')||'en';embedArgs.theme=(wpembed.getAttribute('data-theme')==='dark')?'dark':'light';embedArgs.host=wpembed.getAttribute('data-host');if(wpembed.getAttribute('data-comment-id')){embedArgs.commentID=parseInt(wpembed.getAttribute('data-comment-id'),10);}else if(wpembed.getAttribute('data-post-id')){embedArgs.postID=parseInt(wpembed.getAttribute('data-post-id'),10);}else if(wpembed.getAttribute('data-post-name')){embedArgs.postName=wpembed.getAttribute('data-post-name');}
if(!embedArgs.host||!embedArgs.host.length){return;}
for(arg in embedArgs){if(embedArgs.hasOwnProperty(arg)){iframeURL+=arg+'='+encodeURIComponent(embedArgs[arg])+'&';}}
uniqueID=function(){var id=++wpembedsCounter+'';return'wpembed-'+id;}();iframe.setAttribute('frameborder',0);iframe.setAttribute('id',uniqueID);iframe.setAttribute('name',uniqueID);iframe.setAttribute('scrolling','no');iframe.setAttribute('src',iframeURL.slice(0,-1));iframe.setAttribute('width','100%');wpembed.parentNode.replaceChild(iframe,wpembed);}
window.addEventListener('message',function(message){if(message.origin!=='https://widgets.wp.com'){return;}
var ID=0,data={}.size=0;try{data=JSON.parse(message.data);}catch(e){}
if(data.type!=='wpEmbedMessage'||typeof data.height==='undefined'||typeof data.ID==='undefined'){return;}
ID=parseInt(data.ID.substr('wpembed-'.length),10);size=parseInt(data.height,10);if(ID<1||size<1){return;}
document.getElementsByName('wpembed-'+ID)[0].setAttribute('height',size+'px');},false);};if('function'==typeof domready){domready(widgets);}else{widgets();}})();